# Generated by Django 2.1.8 on 2019-05-18 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ruc', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=55)),
                ('serie', models.CharField(max_length=45)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
