# Generated by Django 2.1.8 on 2019-05-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_auto_20190517_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
