# Generated by Django 2.1.8 on 2019-05-18 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('Invoices', '0004_auto_20190517_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailinvoice',
            name='products',
        ),
        migrations.AddField(
            model_name='detailinvoice',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product'),
            preserve_default=False,
        ),
    ]
