# Generated by Django 2.1.8 on 2019-05-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ruc',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
